### ISSUE TITLE
Undefined name: 'msg'

### ISSUE THREAD

**Issue by cclauss** [IBM/cristata#1]
flake8 testing of https://github.com/IBM/cristata on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./openwhisk/devices.py:49:18: F821 undefined name 'msg'
        result = msg.fail(400, str(e))
                 ^
1     F821 undefined name 'msg'
1
```

**Comment by mkepurcell** [comment]
Fixed in f57cd6f
